[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]
aptPkgs = []

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"