[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodejs = "20"
npm = "9"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
cmds = []



# Exponer ambos puertos en Railway
[networking]
serviceName = "campus-api-academy"

[experimental]
configAsCode = true