[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodejs = "20"
npm = "9"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
cmds = []

[networking]
serviceName = "campus-api-academy"

# Exponer puerto gRPC específicamente
[[networking.exposedPorts]]
port = 50051
protocol = "tcp"

[experimental]
configAsCode = true