[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodejs = "20"
npm = "9"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
cmds = []

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# CRÍTICO: Configurar red privada
[deploy.privatePorts]
port = 50051

[experimental]
configAsCode = true