[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodejs = "20"
npm = "9"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
cmds = []



# Railway hybrid mode: HTTP + gRPC en el mismo puerto
[experimental]
configAsCode = true