[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodejs = "20"
npm = "9"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
cmds = []

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# CRÍTICO: Exponer puerto gRPC para Railway Private Network
[experimental]
configAsCode = true

[networking]
serviceName = "campus-api-academy"
# Permitir conexiones internas en puerto 50051
internalPort = 50051