[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nodejs = "20"
npm = "9"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]
cmds = [
  "chmod +x setup-npm.sh",
  "./setup-npm.sh"
]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start:prod"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[experimental]
configAsCode = true